import { useState, useEffect, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { groupsAPI, membersAPI, expensesAPI, balancesAPI } from '../services/api';
import Analytics from '../components/Analytics';
import { exportToCSV, filterExpenses } from '../utils/helpers';
import toast from 'react-hot-toast';

const SPLIT_METHODS = [
    { key: 'equal', label: 'Equal' },
    { key: 'percentage', label: 'Percent' },
    { key: 'share', label: 'Shares' },
    { key: 'item', label: 'Items' },
];

const CURRENCIES = ['INR', 'USD', 'EUR', 'GBP', 'JPY', 'AUD', 'THB', 'SGD', 'AED'];

// Category icon detection
function getExpenseIcon(title) {
    const t = (title || '').toLowerCase();
    if (t.match(/food|dinner|lunch|breakfast|meal|eat|restaurant|pizza|burger|cafe|coffee/)) return '🍔';
    if (t.match(/hotel|stay|room|airbnb|hostel|lodge/)) return '🏨';
    if (t.match(/taxi|uber|ola|cab|ride|transport|bus|train|metro|flight|travel/)) return '🚕';
    if (t.match(/rent|house|flat|apartment|accommodation/)) return '🏠';
    if (t.match(/petrol|fuel|gas|parking/)) return '⛽';
    if (t.match(/shop|buy|purchase|grocery|mart|market/)) return '🛒';
    if (t.match(/movie|film|cinema|entertainment|game|party/)) return '🎬';
    if (t.match(/bill|electric|water|wifi|internet|phone|recharge/)) return '📱';
    if (t.match(/medical|hospital|medicine|doctor|health/)) return '🏥';
    return '💳';
}

function generateWhatsAppMessage(settlements, groupName, currencySymbol) {
    let msg = `💰 *${groupName} — Settlements*\n\n`;
    settlements.forEach((s) => {
        msg += `${s.from_name} → ${s.to_name}: ${currencySymbol}${s.amount.toLocaleString()}\n`;
    });
    msg += '\n_Generated by Split It Fair_';
    return encodeURIComponent(msg);
}

export default function GroupDetail() {
    const { groupId } = useParams();
    const navigate = useNavigate();
    const [group, setGroup] = useState(null);
    const [members, setMembers] = useState([]);
    const [expenses, setExpenses] = useState([]);
    const [balances, setBalances] = useState([]);
    const [settlements, setSettlements] = useState(null);
    const [loading, setLoading] = useState(true);
    const [activeTab, setActiveTab] = useState('expenses');
    const [showExpenseModal, setShowExpenseModal] = useState(false);
    const [newMember, setNewMember] = useState('');
    const [dashboard, setDashboard] = useState(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [filterMethod, setFilterMethod] = useState('all');

    const [expenseForm, setExpenseForm] = useState({
        title: '', amount: '', currency: 'INR', paid_by: '',
        date: new Date().toISOString().split('T')[0],
        split_method: 'equal', is_recurring: false,
        recurrence_interval: 'monthly', split_details: {}, members: [],
    });

    useEffect(() => { loadAll(); }, [groupId]);

    const filteredExpenses = useMemo(
        () => filterExpenses(expenses, searchQuery, filterMethod),
        [expenses, searchQuery, filterMethod]
    );

    const totalSpent = useMemo(() =>
        expenses.reduce((s, e) => s + parseFloat(e.converted_amount || e.amount), 0), [expenses]
    );

    async function loadAll() {
        try {
            const [groupData, , expenseData] = await Promise.all([
                groupsAPI.get(groupId), membersAPI.list(groupId), expensesAPI.list(groupId),
            ]);
            setGroup(groupData.group);
            setMembers(groupData.group.members || []);
            setExpenses(expenseData.expenses || []);
            setExpenseForm((f) => ({ ...f, currency: groupData.group.base_currency || 'INR' }));
            try {
                const [balData, settData] = await Promise.all([
                    balancesAPI.getBalances(groupId), balancesAPI.getSettlements(groupId),
                ]);
                setBalances(balData.balances || []);
                setSettlements(settData);
            } catch { }
        } catch (err) {
            toast.error('Failed to load group');
            navigate('/app');
        } finally { setLoading(false); }
    }

    async function addMember(e) {
        e.preventDefault();
        if (!newMember.trim()) return;
        try {
            await membersAPI.add(groupId, { name: newMember.trim() });
            setNewMember('');
            toast.success('Member added');
            loadAll();
        } catch (err) { toast.error(err.message); }
    }

    async function removeMember(id) {
        if (!confirm('Remove this member?')) return;
        try { await membersAPI.remove(id); toast.success('Removed'); loadAll(); }
        catch (err) { toast.error(err.message); }
    }

    async function addExpense(e) {
        e.preventDefault();
        if (!expenseForm.title || !expenseForm.amount || !expenseForm.paid_by) {
            return toast.error('Fill in title, amount, and payer');
        }
        try {
            const body = {
                title: expenseForm.title,
                amount: parseFloat(expenseForm.amount),
                currency: expenseForm.currency,
                paid_by: parseInt(expenseForm.paid_by),
                date: expenseForm.date,
                split_method: expenseForm.split_method,
                is_recurring: expenseForm.is_recurring,
                recurrence_interval: expenseForm.is_recurring ? expenseForm.recurrence_interval : null,
                members: expenseForm.members.length > 0 ? expenseForm.members : undefined,
                split_details: {},
            };
            if (expenseForm.split_method === 'percentage') {
                body.split_details.percentages = {};
                members.forEach((m) => {
                    const v = expenseForm.split_details[`pct_${m.id}`];
                    if (v) body.split_details.percentages[m.id] = parseFloat(v);
                });
            } else if (expenseForm.split_method === 'share') {
                body.split_details.shares = {};
                members.forEach((m) => {
                    const v = expenseForm.split_details[`share_${m.id}`];
                    if (v) body.split_details.shares[m.id] = parseFloat(v);
                });
            } else if (expenseForm.split_method === 'item') {
                body.split_details.items = [];
                members.forEach((m) => {
                    const amt = expenseForm.split_details[`item_amt_${m.id}`];
                    const desc = expenseForm.split_details[`item_desc_${m.id}`];
                    if (amt) body.split_details.items.push({ member_id: m.id, amount: parseFloat(amt), description: desc || '' });
                });
            }
            await expensesAPI.create(groupId, body);
            toast.success('Expense added');
            setShowExpenseModal(false);
            resetForm();
            loadAll();
        } catch (err) { toast.error(err.message); }
    }

    function resetForm() {
        setExpenseForm({
            title: '', amount: '', currency: group?.base_currency || 'INR', paid_by: '',
            date: new Date().toISOString().split('T')[0],
            split_method: 'equal', is_recurring: false,
            recurrence_interval: 'monthly', split_details: {}, members: [],
        });
    }

    async function deleteExpense(id) {
        if (!confirm('Delete this expense?')) return;
        try { await expensesAPI.delete(id); toast.success('Deleted'); loadAll(); }
        catch (err) { toast.error(err.message); }
    }

    async function viewDashboard(memberId) {
        try {
            const data = await balancesAPI.getDashboard(groupId, memberId);
            setDashboard(data);
        } catch (err) { toast.error(err.message); }
    }

    function setSplitDetail(key, value) {
        setExpenseForm((f) => ({ ...f, split_details: { ...f.split_details, [key]: value } }));
    }

    if (loading) return <div className="loading-center"><div className="spinner" /></div>;
    if (!group) return null;

    const currencySymbol = group.base_currency === 'INR' ? '₹' : group.base_currency + ' ';
    const totalOwed = balances.filter((b) => b.net_balance > 0).reduce((s, b) => s + b.net_balance, 0);
    const totalDebt = Math.abs(balances.filter((b) => b.net_balance < 0).reduce((s, b) => s + b.net_balance, 0));

    return (
        <div>
            {/* ── Header ─────────────────────────────── */}
            <div style={{ marginBottom: 20 }}>
                <button className="btn btn-secondary btn-sm" onClick={() => navigate('/app')} style={{ marginBottom: 12 }}>
                    ← Back
                </button>
                <div className="section-header" style={{ marginBottom: 0 }}>
                    <div>
                        <h1 className="section-title">{group.name}</h1>
                        <p className="section-subtitle">{members.length} member{members.length !== 1 ? 's' : ''} · {group.base_currency}</p>
                    </div>
                    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                        {expenses.length > 0 && (
                            <button className="btn btn-secondary btn-sm" onClick={() => exportToCSV(expenses, group.name, currencySymbol)}>
                                📥 CSV
                            </button>
                        )}
                    </div>
                </div>
            </div>

            {/* ── Balance Banner ─────────────────────── */}
            {expenses.length > 0 && (
                <div className="balance-banner">
                    <div className="balance-banner-grid">
                        <div className="balance-banner-item">
                            <div className="balance-banner-label">Total Spent</div>
                            <div className="balance-banner-value">{currencySymbol}{totalSpent.toLocaleString(undefined, { maximumFractionDigits: 0 })}</div>
                        </div>
                        <div className="balance-banner-item">
                            <div className="balance-banner-label">Gets Back</div>
                            <div className="balance-banner-value">{currencySymbol}{totalOwed.toFixed(0)}</div>
                        </div>
                        <div className="balance-banner-item">
                            <div className="balance-banner-label">Total Debts</div>
                            <div className="balance-banner-value">{currencySymbol}{totalDebt.toFixed(0)}</div>
                        </div>
                    </div>
                </div>
            )}

            {/* ── Tabs ───────────────────────────────── */}
            <div className="tabs">
                {['expenses', 'members', 'balances', 'settlements', 'analytics'].map((tab) => (
                    <button key={tab} className={`tab ${activeTab === tab ? 'active' : ''}`}
                        onClick={() => setActiveTab(tab)}>
                        {tab.charAt(0).toUpperCase() + tab.slice(1)}
                    </button>
                ))}
            </div>

            {/* ═══ EXPENSES ═══ */}
            {activeTab === 'expenses' && (
                <div>
                    {expenses.length > 0 && (
                        <div className="search-bar">
                            <input className="form-input" placeholder="Search expenses..." value={searchQuery}
                                onChange={(e) => setSearchQuery(e.target.value)} />
                            <select className="form-input" value={filterMethod} onChange={(e) => setFilterMethod(e.target.value)}>
                                <option value="all">All methods</option>
                                <option value="equal">Equal</option>
                                <option value="percentage">Percentage</option>
                                <option value="share">Share</option>
                                <option value="item">Item</option>
                            </select>
                            {(searchQuery || filterMethod !== 'all') && (
                                <span style={{ fontSize: '0.73rem', color: 'var(--text-3)' }}>{filteredExpenses.length} result{filteredExpenses.length !== 1 ? 's' : ''}</span>
                            )}
                        </div>
                    )}

                    {filteredExpenses.length === 0 && expenses.length === 0 ? (
                        <div className="empty-state">
                            <div className="icon">📄</div>
                            <p>No expenses yet. Tap + to add your first expense.</p>
                        </div>
                    ) : filteredExpenses.length === 0 ? (
                        <div className="empty-state">
                            <div className="icon">🔍</div>
                            <p>No expenses match your search.</p>
                        </div>
                    ) : (
                        filteredExpenses.map((exp, i) => (
                            <div key={exp.id} className="expense-item animate-in" style={{ animationDelay: `${i * 0.03}s` }}>
                                <div className="expense-icon">{getExpenseIcon(exp.title)}</div>
                                <div className="expense-info">
                                    <div className="expense-title">
                                        {exp.title}
                                        {exp.is_recurring && <span className="badge badge-gold" style={{ marginLeft: 8 }}>Recurring</span>}
                                    </div>
                                    <div className="expense-meta">
                                        <span>Paid by <strong>{exp.payer?.name || '—'}</strong></span>
                                        <span>·</span>
                                        <span>{new Date(exp.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</span>
                                        <span className="badge badge-neutral">{exp.split_method}</span>
                                        {exp.currency !== group.base_currency && (
                                            <span className="badge badge-purple">{exp.currency} → {group.base_currency}</span>
                                        )}
                                    </div>
                                    {exp.splits && exp.splits.length > 0 && (
                                        <div style={{ marginTop: 5, display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                                            {exp.splits.map((s) => (
                                                <span key={s.id} className="badge badge-blue" style={{ fontSize: '0.63rem' }}>
                                                    {s.member?.name}: {currencySymbol}{parseFloat(s.amount).toFixed(0)}
                                                </span>
                                            ))}
                                        </div>
                                    )}
                                </div>
                                <div style={{ textAlign: 'right', flexShrink: 0 }}>
                                    <div className="expense-amount">
                                        {exp.currency === 'INR' ? '₹' : exp.currency + ' '}{parseFloat(exp.amount).toLocaleString()}
                                    </div>
                                    {exp.converted_amount && exp.currency !== group.base_currency && (
                                        <div className="expense-converted">≈ {currencySymbol}{parseFloat(exp.converted_amount).toLocaleString()}</div>
                                    )}
                                </div>
                                <button className="btn-icon" onClick={() => deleteExpense(exp.id)} title="Delete">✕</button>
                            </div>
                        ))
                    )}
                </div>
            )}

            {/* ═══ MEMBERS ═══ */}
            {activeTab === 'members' && (
                <div>
                    <form onSubmit={addMember} style={{ display: 'flex', gap: 10, marginBottom: 24 }}>
                        <input className="form-input" placeholder="Enter member name..." value={newMember}
                            onChange={(e) => setNewMember(e.target.value)} style={{ maxWidth: 260 }} />
                        <button type="submit" className="btn btn-primary">Add</button>
                    </form>
                    {members.length > 0 ? (
                        <div className="members-list">
                            {members.map((m) => (
                                <div key={m.id} className="member-chip">
                                    {m.name}
                                    <span className="remove" onClick={() => removeMember(m.id)}>✕</span>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="empty-state">
                            <div className="icon">👤</div>
                            <p>Add members to start splitting expenses.</p>
                        </div>
                    )}
                </div>
            )}

            {/* ═══ BALANCES ═══ */}
            {activeTab === 'balances' && (
                <div>
                    {balances.map((b, i) => (
                        <div key={b.member_id} className="expense-item animate-in"
                            style={{ animationDelay: `${i * 0.04}s`, cursor: 'pointer' }}
                            onClick={() => viewDashboard(b.member_id)}>
                            <div className="expense-icon" style={{
                                background: b.status === 'is_owed' ? 'var(--green-soft)' : b.status === 'owes' ? 'var(--red-soft)' : 'var(--primary-soft)'
                            }}>
                                {b.status === 'is_owed' ? '🟢' : b.status === 'owes' ? '🔴' : '🔵'}
                            </div>
                            <div className="expense-info">
                                <div className="expense-title">{b.member_name}</div>
                                <div className="expense-meta">
                                    <span className={`badge ${b.status === 'is_owed' ? 'badge-green' : b.status === 'owes' ? 'badge-red' : 'badge-blue'}`}>
                                        {b.status === 'is_owed' ? 'Gets back' : b.status === 'owes' ? 'Owes' : 'Settled'}
                                    </span>
                                    <span style={{ color: 'var(--text-3)', fontSize: '0.7rem' }}>Tap for details →</span>
                                </div>
                            </div>
                            <div className="expense-amount" style={{
                                color: b.net_balance > 0 ? 'var(--green)' : b.net_balance < 0 ? 'var(--red)' : 'var(--text-3)'
                            }}>
                                {b.net_balance >= 0 ? '+' : ''}{currencySymbol}{b.net_balance.toFixed(2)}
                            </div>
                        </div>
                    ))}

                    {balances.length === 0 && (
                        <div className="empty-state">
                            <div className="icon">📊</div>
                            <p>Add expenses to see member balances.</p>
                        </div>
                    )}

                    {dashboard && (
                        <div className="modal-overlay" onClick={() => setDashboard(null)}>
                            <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 440 }}>
                                <h2 className="modal-title">{dashboard.member.name}'s Dashboard</h2>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 20 }}>
                                    <div className="stat-card stat-green">
                                        <div className="stat-label">Owed to you</div>
                                        <div className="stat-value" style={{ fontSize: '1.2rem' }}>{currencySymbol}{dashboard.summary.total_owed_to_you.toFixed(0)}</div>
                                    </div>
                                    <div className="stat-card stat-red">
                                        <div className="stat-label">You owe</div>
                                        <div className="stat-value" style={{ fontSize: '1.2rem' }}>{currencySymbol}{dashboard.summary.total_you_owe.toFixed(0)}</div>
                                    </div>
                                </div>
                                <div style={{ textAlign: 'center', marginBottom: 18, padding: 14, background: 'var(--bg-2)', borderRadius: 'var(--radius-md)' }}>
                                    <span style={{ fontSize: '0.72rem', color: 'var(--text-3)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.04em' }}>Net balance</span>
                                    <div style={{ fontSize: '1.4rem', fontWeight: 800, color: dashboard.summary.net_balance >= 0 ? 'var(--green)' : 'var(--red)', marginTop: 4 }}>
                                        {dashboard.summary.net_balance >= 0 ? '+' : ''}{currencySymbol}{dashboard.summary.net_balance.toFixed(2)}
                                    </div>
                                </div>
                                {dashboard.details.length > 0 ? dashboard.details.map((d, i) => (
                                    <div key={i} className="settlement-item"><span style={{ flex: 1, fontSize: '0.85rem' }}>{d.description}</span></div>
                                )) : <p style={{ textAlign: 'center', color: 'var(--text-3)', padding: 16 }}>All settled up! ✓</p>}
                                <div className="modal-actions"><button className="btn btn-secondary" onClick={() => setDashboard(null)}>Close</button></div>
                            </div>
                        </div>
                    )}
                </div>
            )}

            {/* ═══ SETTLEMENTS ═══ */}
            {activeTab === 'settlements' && (
                <div>
                    {settlements && settlements.settlements.length > 0 ? (
                        <>
                            <div style={{ display: 'flex', gap: 12, marginBottom: 20 }}>
                                <div className="stat-card" style={{ flex: 1, textAlign: 'center' }}>
                                    <div className="stat-label">Transactions needed</div>
                                    <div className="stat-value" style={{ color: 'var(--primary)' }}>{settlements.total_transactions}</div>
                                </div>
                                <a
                                    href={`https://wa.me/?text=${generateWhatsAppMessage(settlements.settlements, group.name, currencySymbol)}`}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="btn btn-whatsapp"
                                    style={{ alignSelf: 'center' }}
                                >
                                    📲 Share via WhatsApp
                                </a>
                            </div>
                            {settlements.settlements.map((s, i) => (
                                <div key={i} className="settlement-item animate-in" style={{ animationDelay: `${i * 0.04}s` }}>
                                    <span style={{ fontWeight: 600, fontSize: '0.88rem' }}>{s.from_name}</span>
                                    <span className="settlement-arrow">→</span>
                                    <span style={{ fontWeight: 600, fontSize: '0.88rem' }}>{s.to_name}</span>
                                    <span className="settlement-amount">{currencySymbol}{s.amount.toLocaleString()}</span>
                                </div>
                            ))}
                        </>
                    ) : (
                        <div className="empty-state">
                            <div className="icon">✓</div>
                            <p>Everyone is squared up — no settlements needed!</p>
                        </div>
                    )}
                </div>
            )}

            {/* ═══ ANALYTICS ═══ */}
            {activeTab === 'analytics' && <Analytics expenses={expenses} members={members} group={group} />}

            {/* ── FAB ────────────────────────────────── */}
            <button className="fab" onClick={() => setShowExpenseModal(true)} title="Add expense">
                +
            </button>

            {/* ═══ ADD EXPENSE MODAL ═══ */}
            {showExpenseModal && (
                <div className="modal-overlay" onClick={() => setShowExpenseModal(false)}>
                    <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 520 }}>
                        <h2 className="modal-title">Add Expense</h2>
                        <form onSubmit={addExpense}>
                            <div className="form-group">
                                <label>Title</label>
                                <input className="form-input" placeholder="Dinner, Hotel, Taxi..." value={expenseForm.title}
                                    onChange={(e) => setExpenseForm({ ...expenseForm, title: e.target.value })} autoFocus />
                            </div>
                            <div className="form-row">
                                <div className="form-group">
                                    <label>Amount</label>
                                    <input className="form-input" type="number" step="0.01" placeholder="0.00" value={expenseForm.amount}
                                        onChange={(e) => setExpenseForm({ ...expenseForm, amount: e.target.value })} />
                                </div>
                                <div className="form-group">
                                    <label>Currency</label>
                                    <select className="form-input" value={expenseForm.currency}
                                        onChange={(e) => setExpenseForm({ ...expenseForm, currency: e.target.value })}>
                                        {CURRENCIES.map((c) => <option key={c} value={c}>{c}</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-row">
                                <div className="form-group">
                                    <label>Paid by</label>
                                    <select className="form-input" value={expenseForm.paid_by}
                                        onChange={(e) => setExpenseForm({ ...expenseForm, paid_by: e.target.value })}>
                                        <option value="">Select...</option>
                                        {members.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label>Date</label>
                                    <input className="form-input" type="date" value={expenseForm.date}
                                        onChange={(e) => setExpenseForm({ ...expenseForm, date: e.target.value })} />
                                </div>
                            </div>
                            <div className="form-group">
                                <label>Split method</label>
                                <div className="split-tabs">
                                    {SPLIT_METHODS.map((s) => (
                                        <button key={s.key} type="button"
                                            className={`split-tab ${expenseForm.split_method === s.key ? 'active' : ''}`}
                                            onClick={() => setExpenseForm({ ...expenseForm, split_method: s.key, split_details: {} })}>
                                            {s.label}
                                        </button>
                                    ))}
                                </div>
                            </div>
                            {expenseForm.split_method === 'percentage' && (
                                <div className="form-group">
                                    <label>Percentage per member (must total 100)</label>
                                    {members.map((m) => (
                                        <div key={m.id} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                                            <span style={{ minWidth: 72, fontSize: '0.82rem', fontWeight: 500 }}>{m.name}</span>
                                            <input className="form-input" type="number" step="0.01" placeholder="0" style={{ maxWidth: 90 }}
                                                value={expenseForm.split_details[`pct_${m.id}`] || ''} onChange={(e) => setSplitDetail(`pct_${m.id}`, e.target.value)} />
                                            <span style={{ color: 'var(--text-3)', fontSize: '0.82rem' }}>%</span>
                                        </div>
                                    ))}
                                </div>
                            )}
                            {expenseForm.split_method === 'share' && (
                                <div className="form-group">
                                    <label>Shares per member</label>
                                    {members.map((m) => (
                                        <div key={m.id} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                                            <span style={{ minWidth: 72, fontSize: '0.82rem', fontWeight: 500 }}>{m.name}</span>
                                            <input className="form-input" type="number" step="0.5" placeholder="1" style={{ maxWidth: 90 }}
                                                value={expenseForm.split_details[`share_${m.id}`] || ''} onChange={(e) => setSplitDetail(`share_${m.id}`, e.target.value)} />
                                            <span style={{ color: 'var(--text-3)', fontSize: '0.82rem' }}>×</span>
                                        </div>
                                    ))}
                                </div>
                            )}
                            {expenseForm.split_method === 'item' && (
                                <div className="form-group">
                                    <label>Assign items</label>
                                    {members.map((m) => (
                                        <div key={m.id} style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}>
                                            <span style={{ minWidth: 72, fontSize: '0.82rem', fontWeight: 500 }}>{m.name}</span>
                                            <input className="form-input" placeholder="Item" style={{ flex: 1 }}
                                                value={expenseForm.split_details[`item_desc_${m.id}`] || ''} onChange={(e) => setSplitDetail(`item_desc_${m.id}`, e.target.value)} />
                                            <input className="form-input" type="number" step="0.01" placeholder="₹" style={{ maxWidth: 80 }}
                                                value={expenseForm.split_details[`item_amt_${m.id}`] || ''} onChange={(e) => setSplitDetail(`item_amt_${m.id}`, e.target.value)} />
                                        </div>
                                    ))}
                                </div>
                            )}
                            <div className="form-group" style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                <input type="checkbox" id="recurring" checked={expenseForm.is_recurring}
                                    onChange={(e) => setExpenseForm({ ...expenseForm, is_recurring: e.target.checked })} />
                                <label htmlFor="recurring" style={{ margin: 0, textTransform: 'none', letterSpacing: 0, fontSize: '0.85rem', fontWeight: 500 }}>
                                    Recurring expense
                                </label>
                                {expenseForm.is_recurring && (
                                    <select className="form-input" style={{ maxWidth: 120 }} value={expenseForm.recurrence_interval}
                                        onChange={(e) => setExpenseForm({ ...expenseForm, recurrence_interval: e.target.value })}>
                                        <option value="monthly">Monthly</option><option value="weekly">Weekly</option>
                                    </select>
                                )}
                            </div>
                            <div className="modal-actions">
                                <button type="button" className="btn btn-secondary" onClick={() => { setShowExpenseModal(false); resetForm(); }}>Cancel</button>
                                <button type="submit" className="btn btn-primary">Add Expense</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
