import { useState, useEffect, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { groupsAPI, membersAPI, expensesAPI, balancesAPI } from '../services/api';
import Analytics from '../components/Analytics';
import { exportToCSV, filterExpenses } from '../utils/helpers';
import toast from 'react-hot-toast';

const SPLIT_METHODS = [
    { key: 'equal', label: 'Equal' },
    { key: 'percentage', label: 'Percent' },
    { key: 'share', label: 'Shares' },
    { key: 'item', label: 'Items' },
];

const CURRENCIES = ['INR', 'USD', 'EUR', 'GBP', 'JPY', 'AUD', 'THB', 'SGD', 'AED'];

// Category icon detection
function getExpenseIcon(title) {
    const t = (title || '').toLowerCase();
    if (t.match(/food|dinner|lunch|breakfast|meal|eat|restaurant|pizza|burger|cafe|coffee/)) return '🍔';
    if (t.match(/hotel|stay|room|airbnb|hostel|lodge/)) return '🏨';
    if (t.match(/taxi|uber|ola|cab|ride|transport|bus|train|metro|flight|travel/)) return '🚕';
    if (t.match(/rent|house|flat|apartment|accommodation/)) return '🏠';
    if (t.match(/petrol|fuel|gas|parking/)) return '⛽';
    if (t.match(/shop|buy|purchase|grocery|mart|market/)) return '🛒';
    if (t.match(/movie|film|cinema|entertainment|game|party/)) return '🎬';
    if (t.match(/bill|electric|water|wifi|internet|phone|recharge/)) return '📱';
    if (t.match(/medical|hospital|medicine|doctor|health/)) return '🏥';
    return '💳';
}

function generateWhatsAppMessage(settlements, groupName, currencySymbol) {
    let msg = `💰 *${groupName} — Settlements*\n\n`;
    settlements.forEach((s) => {
        msg += `${s.from_name} → ${s.to_name}: ${currencySymbol}${s.amount.toLocaleString()}\n`;
    });
    msg += '\n_Generated by Split It Fair_';
    return encodeURIComponent(msg);
}

export default function GroupDetail() {
    const { groupId } = useParams();
    const navigate = useNavigate();
    const [group, setGroup] = useState(null);
    const [members, setMembers] = useState([]);
    const [expenses, setExpenses] = useState([]);
    const [balances, setBalances] = useState([]);
    const [settlements, setSettlements] = useState(null);
    const [loading, setLoading] = useState(true);
    const [activeTab, setActiveTab] = useState('expenses');
    const [showExpenseModal, setShowExpenseModal] = useState(false);
    const [newMember, setNewMember] = useState('');
    const [dashboard, setDashboard] = useState(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [filterMethod, setFilterMethod] = useState('all');

    const [expenseForm, setExpenseForm] = useState({
        title: '', amount: '', currency: 'INR', paid_by: '',
        date: new Date().toISOString().split('T')[0],
        split_method: 'equal', is_recurring: false,
        recurrence_interval: 'monthly', split_details: {}, members: [],
    });

    useEffect(() => { loadAll(); }, [groupId]);

    const filteredExpenses = useMemo(
        () => filterExpenses(expenses, searchQuery, filterMethod),
        [expenses, searchQuery, filterMethod]
    );

    const totalSpent = useMemo(() =>
        expenses.reduce((s, e) => s + parseFloat(e.converted_amount || e.amount), 0), [expenses]
    );

    async function loadAll() {
        try {
            const [groupData, , expenseData] = await Promise.all([
                groupsAPI.get(groupId), membersAPI.list(groupId), expensesAPI.list(groupId),
            ]);
            setGroup(groupData.group);
            setMembers(groupData.group.members || []);
            setExpenses(expenseData.expenses || []);
            setExpenseForm((f) => ({ ...f, currency: groupData.group.base_currency || 'INR' }));
            try {
                const [balData, settData] = await Promise.all([
                    balancesAPI.getBalances(groupId), balancesAPI.getSettlements(groupId),
                ]);
                setBalances(balData.balances || []);
                setSettlements(settData);
            } catch { }
        } catch (err) {
            toast.error('Failed to load group');
            navigate('/app');
        } finally { setLoading(false); }
    }

    async function addMember(e) {
        e.preventDefault();
        if (!newMember.trim()) return;
        try {
            await membersAPI.add(groupId, { name: newMember.trim() });
            setNewMember('');
            toast.success('Member added');
            loadAll();
        } catch (err) { toast.error(err.message); }
    }

    async function removeMember(id) {
        if (!confirm('Remove this member?')) return;
        try { await membersAPI.remove(id); toast.success('Removed'); loadAll(); }
        catch (err) { toast.error(err.message); }
    }

    async function addExpense(e) {
        e.preventDefault();
        if (!expenseForm.title || !expenseForm.amount || !expenseForm.paid_by) {
            return toast.error('Fill in title, amount, and payer');
        }
        try {
            const body = {
                title: expenseForm.title,
                amount: parseFloat(expenseForm.amount),
                currency: expenseForm.currency,
                paid_by: parseInt(expenseForm.paid_by),
                date: expenseForm.date,
                split_method: expenseForm.split_method,
                is_recurring: expenseForm.is_recurring,
                recurrence_interval: expenseForm.is_recurring ? expenseForm.recurrence_interval : null,
                members: expenseForm.members.length > 0 ? expenseForm.members : undefined,
                split_details: {},
            };
            if (expenseForm.split_method === 'percentage') {
                body.split_details.percentages = {};
                members.forEach((m) => {
                    const v = expenseForm.split_details[`pct_${m.id}`];
                    if (v) body.split_details.percentages[m.id] = parseFloat(v);
                });
            } else if (expenseForm.split_method === 'share') {
                body.split_details.shares = {};
                members.forEach((m) => {
                    const v = expenseForm.split_details[`share_${m.id}`];
                    if (v) body.split_details.shares[m.id] = parseFloat(v);
                });
            } else if (expenseForm.split_method === 'item') {
                body.split_details.items = [];
                members.forEach((m) => {
                    const amt = expenseForm.split_details[`item_amt_${m.id}`];
                    const desc = expenseForm.split_details[`item_desc_${m.id}`];
                    if (amt) body.split_details.items.push({ member_id: m.id, amount: parseFloat(amt), description: desc || '' });
                });
            }
            await expensesAPI.create(groupId, body);
            toast.success('Expense added');
            setShowExpenseModal(false);
            resetForm();
            loadAll();
        } catch (err) { toast.error(err.message); }
    }

    function resetForm() {
        setExpenseForm({
            title: '', amount: '', currency: group?.base_currency || 'INR', paid_by: '',
            date: new Date().toISOString().split('T')[0],
            split_method: 'equal', is_recurring: false,
            recurrence_interval: 'monthly', split_details: {}, members: [],
        });
    }

    async function deleteExpense(id) {
        if (!confirm('Delete this expense?')) return;
        try { await expensesAPI.delete(id); toast.success('Deleted'); loadAll(); }
        catch (err) { toast.error(err.message); }
    }

    async function viewDashboard(memberId) {
        try {
            const data = await balancesAPI.getDashboard(groupId, memberId);
            setDashboard(data);
        } catch (err) { toast.error(err.message); }
    }

    function setSplitDetail(key, value) {
        setExpenseForm((f) => ({ ...f, split_details: { ...f.split_details, [key]: value } }));
    }

    if (loading) return <div className="loading-center"><div className="spinner" /></div>;
    if (!group) return null;

    const currencySymbol = group.base_currency === 'INR' ? '₹' : group.base_currency + ' ';
    const totalOwed = balances.filter((b) => b.net_balance > 0).reduce((s, b) => s + b.net_balance, 0);
    const totalDebt = Math.abs(balances.filter((b) => b.net_balance < 0).reduce((s, b) => s + b.net_balance, 0));

    // Auto settlement best link logic
    const bestSettlement = settlements?.settlements?.length > 0
        ? settlements.settlements.reduce((prev, curr) => prev.amount > curr.amount ? prev : curr)
        : null;

    return (
        <div className="group-detail-page">
            {/* ── Custom Header ───────────────────────── */}
            <div className="app-header-custom">
                <div className="logo-area" onClick={() => navigate('/app')} style={{cursor: 'pointer'}}>
                    <span style={{ fontSize: '1.4rem', marginRight: 4 }}>≡</span>
                    SplitIt
                </div>
                <div className="user-area">
                    <span>{group.name}</span>
                    <div className="ib-avatar" style={{width: 32, height: 32}}>
                        <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${group.id}`} alt="Group" />
                    </div>
                </div>
            </div>

            {/* ── Total Balance ───────────────────────── */}
            <div className="total-balance-card shadow-lg">
                <div className="total-balance-label">Total Group Balance</div>
                <div className="total-balance-value">{currencySymbol}{totalSpent.toLocaleString(undefined, { maximumFractionDigits: 0 })}</div>
                <div className="total-balance-pill">
                    <span>💵</span> {totalDebt > 0 ? 'You owe overall' : 'You get back overall'}
                </div>
            </div>

            {/* ── Balances ────────────────────────────── */}
            {balances.length > 0 && (
                <>
                    <div className="section-label">Individual Balances</div>
                    <div className="individual-balances-wrapper">
                        {balances.map((b, i) => (
                            <div key={b.member_id} className="individual-balance-card animate-in" style={{ animationDelay: `${i * 0.04}s` }} onClick={() => viewDashboard(b.member_id)}>
                                <div className="ib-user">
                                    <div className="ib-avatar">
                                        <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${b.member_id}`} alt="avatar" />
                                    </div>
                                    <div className="ib-name">{b.member_name}</div>
                                </div>
                                <div style={{marginTop: 'auto', paddingTop: 16}}>
                                    <div className="ib-status">
                                        {b.status === 'is_owed' ? 'Owes you' : b.status === 'owes' ? 'You owe' : 'Settled'}
                                    </div>
                                    <div className={`ib-amount ${b.status === 'is_owed' ? 'green' : b.status === 'owes' ? 'owe' : 'settled'}`}>
                                        {currencySymbol}{Math.abs(b.net_balance).toLocaleString()}
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </>
            )}

            {/* ── Smart Settlement ────────────────────── */}
            {bestSettlement && (
                <div className="smart-settlement-box animate-in">
                    <div className="smart-settlement-content">
                        <div className="smart-settlement-title">
                            <span style={{color: 'var(--primary)'}}>✨</span> Smart Settlement
                        </div>
                        <div className="smart-settlement-desc">
                            We've calculated the most efficient way to settle all your debts within this group.
                        </div>
                    </div>
                    <div className="smart-settlement-action">
                        Pay <strong>{currencySymbol}{bestSettlement.amount.toLocaleString()}</strong> to <strong>{bestSettlement.to_name}</strong> to settle dues.
                        <div className="smart-progress"><div className="smart-progress-bar"></div></div>
                    </div>
                </div>
            )}

            {/* ── Recent Transactions ─────────────────── */}
            <div className="section-label" style={{marginTop: 16}}>
                <span>Recent Transactions</span>
                <span style={{fontSize: '0.75rem', color: 'var(--primary)', cursor: 'pointer', textTransform: 'uppercase'}} onClick={() => window.scrollTo({top: 0, behavior: 'smooth'})}>VIEW ALL</span>
            </div>
            <div style={{marginBottom: 32}}>
                {expenses.length === 0 ? (
                    <div className="empty-state" style={{padding: '24px 0'}}>
                        <p>No expenses yet.</p>
                    </div>
                ) : (
                    expenses.slice(0, 5).map((exp, i) => (
                        <div key={exp.id} className="expense-item animate-in" style={{ animationDelay: `${i * 0.03}s` }}>
                            <div className="expense-icon" style={{ borderRadius: '50%', background: 'var(--bg-2)' }}>{getExpenseIcon(exp.title)}</div>
                            <div className="expense-info">
                                <div className="expense-title">{exp.title}</div>
                                <div className="expense-meta">
                                    {new Date(exp.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} · Paid by {exp.payer?.name || '—'}
                                </div>
                            </div>
                            <div style={{ textAlign: 'right', flexShrink: 0 }}>
                                <div className="expense-amount" style={{fontSize: '0.95rem', color: exp.paid_by == 1 ? 'var(--text-0)' : 'var(--red)'}}> 
                                    {exp.currency === 'INR' ? '₹' : exp.currency + ' '}{parseFloat(exp.amount).toLocaleString()}
                                </div>
                                <div className="expense-converted" style={{textTransform: 'uppercase', fontSize: '0.65rem'}}>YOUR SHARE</div>
                            </div>
                            <button className="btn-icon" onClick={() => deleteExpense(exp.id)} title="Delete" style={{marginLeft: 8}}>✕</button>
                        </div>
                    ))
                )}
            </div>

            {/* ── FAB and Bottom Nav ───────────────────── */}
            <button className="fab-center" onClick={() => setShowExpenseModal(true)}>
                💵 Settle Up Now
            </button>

            <div className="bottom-nav">
                <button className="bottom-nav-item active" onClick={() => navigate('/app')}>
                    <div className="bottom-nav-icon">👥</div>
                    Groups
                </button>
                <button className="bottom-nav-item">
                    <div className="bottom-nav-icon">👤</div>
                    Friends
                </button>
                <button className="bottom-nav-item" onClick={() => setActiveTab('analytics')}>
                    <div className="bottom-nav-icon">⏱️</div>
                    Activity
                </button>
                <button className="bottom-nav-item">
                    <div className="bottom-nav-icon">⚙️</div>
                    Account
                </button>
            </div>

            {/* ── Modals ──────────────────────────────── */}
            {dashboard && (
                <div className="modal-overlay" onClick={() => setDashboard(null)}>
                    <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 440 }}>
                        <h2 className="modal-title">{dashboard.member.name}'s Dashboard</h2>
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 20 }}>
                            <div className="stat-card stat-green">
                                <div className="stat-label">Owed to you</div>
                                <div className="stat-value" style={{ fontSize: '1.2rem' }}>{currencySymbol}{dashboard.summary.total_owed_to_you.toFixed(0)}</div>
                            </div>
                            <div className="stat-card stat-red">
                                <div className="stat-label">You owe</div>
                                <div className="stat-value" style={{ fontSize: '1.2rem' }}>{currencySymbol}{dashboard.summary.total_you_owe.toFixed(0)}</div>
                            </div>
                        </div>
                        <div style={{ textAlign: 'center', marginBottom: 18, padding: 14, background: 'var(--bg-2)', borderRadius: 'var(--radius-md)' }}>
                            <span style={{ fontSize: '0.72rem', color: 'var(--text-3)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.04em' }}>Net balance</span>
                            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: dashboard.summary.net_balance >= 0 ? 'var(--green)' : 'var(--red)', marginTop: 4 }}>
                                {dashboard.summary.net_balance >= 0 ? '+' : ''}{currencySymbol}{dashboard.summary.net_balance.toFixed(2)}
                            </div>
                        </div>
                        {dashboard.details.length > 0 ? dashboard.details.map((d, i) => (
                            <div key={i} className="settlement-item"><span style={{ flex: 1, fontSize: '0.85rem' }}>{d.description}</span></div>
                        )) : <p style={{ textAlign: 'center', color: 'var(--text-3)', padding: 16 }}>All settled up! ✓</p>}
                        <div className="modal-actions"><button className="btn btn-secondary" onClick={() => setDashboard(null)}>Close</button></div>
                    </div>
                </div>
            )}

            {/* ═══ ADD EXPENSE MODAL (MODERN UI) ═══ */}
            {showExpenseModal && (
                <div className="modal-overlay" style={{background: 'var(--bg-0)', display: 'flex'}} onClick={() => {}}>
                    <div className="modal" style={{ width: '100%', height: '100%', maxWidth: '100%', maxHeight: '100%', borderRadius: 0, padding: 0, overflowY: 'auto', display: 'flex', flexDirection: 'column' }} onClick={(e) => e.stopPropagation()}>
                        
                        <div style={{ padding: '20px 24px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'white', position: 'sticky', top: 0, zIndex: 10 }}>
                            <button className="btn-icon" onClick={() => { setShowExpenseModal(false); resetForm(); }} style={{ color: 'var(--primary)', fontWeight: 600, fontSize: '1.05rem', background: 'transparent' }}>
                                Cancel
                            </button>
                            <h2 style={{ fontSize: '1.1rem', fontWeight: 700 }}>Add charge</h2>
                            <div style={{ width: 60 }}></div> {/* spacer */}
                        </div>

                        <form onSubmit={addExpense} style={{ flex: 1, padding: '24px', display: 'flex', flexDirection: 'column', paddingBottom: 100 }}>
                            
                            <input 
                                style={{ fontSize: '2rem', fontWeight: 800, border: 'none', background: 'transparent', outline: 'none', marginBottom: 32, width: '100%', letterSpacing: '-0.5px' }}
                                placeholder="What was this for?" 
                                value={expenseForm.title}
                                onChange={(e) => setExpenseForm({ ...expenseForm, title: e.target.value })} 
                                autoFocus 
                            />

                            <div className="sub-heading-small" style={{marginBottom: 16}}>HOW MUCH?</div>
                            <div className="input-huge-wrapper" style={{background: 'transparent', padding: 0, marginBottom: 40}}>
                                <span className="input-huge-currency">{group.base_currency === 'INR' ? '₹' : group.base_currency}</span>
                                <input 
                                    className="input-huge" 
                                    type="number" 
                                    step="0.01" 
                                    placeholder="0" 
                                    value={expenseForm.amount}
                                    onChange={(e) => setExpenseForm({ ...expenseForm, amount: e.target.value })} 
                                />
                            </div>

                            <div className="sub-heading-small" style={{marginBottom: 16}}>PAID BY</div>
                            <div className="pill-list-horizontal" style={{marginBottom: 40}}>
                                {members.map(m => (
                                    <div 
                                        key={m.id} 
                                        className={`modern-pill ${expenseForm.paid_by === m.id ? 'active' : ''}`}
                                        onClick={() => setExpenseForm({ ...expenseForm, paid_by: m.id })}
                                    >
                                        <div className="pill-avatar">
                                            <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${m.id}`} alt={m.name} />
                                        </div>
                                        {m.name === 'Gurukant Patil' ? 'Me' : m.name}
                                    </div>
                                ))}
                            </div>

                            <div className="sub-heading-small" style={{marginBottom: 16}}>SPLIT WITH</div>
                            <div style={{marginBottom: 20}}>
                                {members.map(m => {
                                    // By default Mockup assumes EQUAL split for simplicity. If we want complex splits we can handle them, but Mockup 3 is a simple checklist.
                                    // For now, let's just make all checked (since it defaults to equal split among group).
                                    // We can simulate checkboxes for visual, though "core logic" for equal split uses all members.
                                    return (
                                        <div key={m.id} className="member-row-modern">
                                            <div className="member-row-avatar">
                                                <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${m.id}`} alt={m.name} />
                                            </div>
                                            <div className="member-row-info">
                                                <div className="member-row-name" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                                                    {m.name === 'Gurukant Patil' ? 'Me' : m.name}
                                                    {m.name === 'Gurukant Patil' && <span className="badge-organizer">Organizer</span>}
                                                </div>
                                                <div className="member-row-sub">
                                                    {expenseForm.amount && expenseForm.split_method === 'equal' 
                                                        ? `${group.base_currency === 'INR' ? '₹' : group.base_currency}${(expenseForm.amount / members.length).toFixed(2)} / person` 
                                                        : 'Included'}
                                                </div>
                                            </div>
                                            <div className="check-circle checked">
                                                ✓
                                            </div>
                                        </div>
                                    )
                                })}
                            </div>

                            {/* Advanced Split Options (hidden behind a toggle or just grouped) */}
                            <details style={{marginBottom: 32}}>
                                <summary style={{fontSize: '0.85rem', color: 'var(--primary)', fontWeight: 600, cursor: 'pointer', outline: 'none'}}>More Options (Date, Advanced Split)</summary>
                                <div style={{marginTop: 16, padding: '16px', background: 'var(--bg-0)', borderRadius: 24}}>
                                    <div className="form-group">
                                        <label>Date</label>
                                        <input className="form-input" type="date" value={expenseForm.date} onChange={(e) => setExpenseForm({ ...expenseForm, date: e.target.value })} style={{background: 'white', border: 'none', borderRadius: 12, padding: 12}} />
                                    </div>
                                    <div className="form-group">
                                        <label>Split method</label>
                                        <div className="split-tabs" style={{background: 'white', borderRadius: 12, padding: 4}}>
                                            {SPLIT_METHODS.map((s) => (
                                                <button key={s.key} type="button"
                                                    className={`split-tab ${expenseForm.split_method === s.key ? 'active' : ''}`}
                                                    onClick={() => setExpenseForm({ ...expenseForm, split_method: s.key, split_details: {} })}
                                                    style={{borderRadius: 8, flex: 1}}>
                                                    {s.label}
                                                </button>
                                            ))}
                                        </div>
                                    </div>
                                    {expenseForm.split_method !== 'equal' && <div style={{fontSize: '0.8rem', color: 'var(--text-2)'}}>Advanced splitting configured by percentages/shares requires precise setup. Defaults to equal.</div>}
                                </div>
                            </details>

                            <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, padding: '20px 24px', background: 'linear-gradient(to top, white 80%, transparent)' }}>
                                <button type="submit" className="large-primary-btn" disabled={loading}>
                                    {loading ? 'Adding...' : expenseForm.amount && !isNaN(expenseForm.amount) && expenseForm.amount > 0 ? `Add ${group.base_currency === 'INR' ? '₹' : group.base_currency}${(expenseForm.amount / members.length).toFixed(2)} / person` : 'Add Expense' }
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
